### ISSUE TITLE
Unable to install Capsule latest version on AKS cluster

### ISSUE THREAD

**Issue by saikumar0412** [clastix/coaks-baseline-architecture#20] opened 2024-09-23 10:38 UTC
I am trying to install capsule on AKS 1.30.3 and unable to succeed with the installation capsule controller is going into crashloop.

I suspect like its the issue with the docker image of capsule it self as its unable to start the entrypoint. kindly help me to get this isse resolved.

```
 Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/manager": stat /manager: no such file or directory: unknown
```

**Comment by prometherion** [comment] 2024-09-23 12:23
@saikumar0412 I think you just need to use the latest Helm Chart for Capsule, or simply remove the `command` which has been changed since switching over `ko` as builder.

**Comment by saikumar0412** [comment] 2024-09-23 12:50
Thanks for the help, I am trying to pull the latest version of the helm chart, but unable to pull the latest helmchart locally.

I reffered the actual repo to fetch 0.6.0 is the latest version correct me if am wrong.
https://github.com/projectcapsule/capsule/blob/main/charts/capsule/Chart.yaml
```
$ helm pull clastix/capsule --version 0.6.0
Error: chart "capsule" matching 0.6.0 not found in clastix index. (try 'helm repo update'): no chart version found for capsule-0.6.0
```

**Comment by prometherion** [comment] 2024-09-23 21:13
Capsule has been donated to the CNCF on the Sandbox area, please, follow the instructions available in the repository of Project Capsule.

Then, it would be appreciated if this repository receives the updated instructions to install according to the latest changes.

**Comment by prometherion** [comment] 2024-09-24 16:09
Regarding the issue, it seems Capsule hasn't yet provisioned HTTPS certificates required for the Dynamic Admission 
Controllers, we should get more information and debug info to properly understand what's not going on.

> Also please do let me know if you have any enterprise version we would like to initiate a discussion about it.
We offer Support over Capsule in delivering an enterprise distribution of Capsule, please get in touch [here](https://clastix.io/support).

**Comment by saikumar0412** [comment] 2024-09-25 07:28
@prometherion Thanks for sharing your input. I have saved your support plan details, will get in touch once we complete PoC and have how many internaly users are interested in it. But currently could you point out where the issue possibly couldbe.

About AKS cluster:

Private AKS cluster with outbound UDR. all the required ports are whitelisted. apart from that we dont have any restrictions.

**Comment by saikumar0412** [comment] 2024-09-25 07:31
Also I see from helm templates I can see certmanager issuer object has been created. do we need certmanager as dependency for using capsule?

**Comment by saikumar0412** [comment] 2024-09-26 18:58
@prometherion could you please check once, if you can mention things that I need to cross check it would be really appreciated.

**Comment by saikumar0412** [comment] 2024-09-27 09:28
@prometherion I have managed to get through the tls related error, now the problem am facing is I have created a tenant with below config

``` apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: user
spec:
  owners:
  - name: emailofuser
    kind: User
  namespaceOptions:
    quota: 2
```

even though he is the owner of the tenant, he is getting forbidden error while creating a new namespace, (Also this user has AKS cluster User role assigned) but still cant create a ns.

**Comment by prometherion** [comment] 2024-10-03 14:11
@saikumar0412 I'm going to close this issue since it's not the proper tool to get support, but a way to report confirmed bugs.

Please, engage with the community on Kubernetes' Slack workspace (channel [#capsule](https://kubernetes.slack.com/archives/C03GETTJQRL)).

**Closed by prometherion** 2024-10-03 14:11 UTC
Labels: question
